# Generated by Django 5.0.1 on 2024-01-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
