# Generated by Django 5.0.1 on 2024-02-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_entry_delete_blogentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entry',
            new_name='BlogEntry',
        ),
    ]
