# Generated by Django 5.0.1 on 2024-02-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_aa_delete_blogentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aa',
            new_name='BlogEntry',
        ),
    ]
