# Generated by Django 5.0.1 on 2024-02-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_rename_aa_blogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='imgLogo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='imgUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
