# Generated by Django 5.0.1 on 2024-02-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_blogentry_imglogo_alter_blogentry_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='content_list',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='resume',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
