# Generated by Django 5.0.1 on 2024-02-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_user_alter_blogentry_content_list_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
