# Generated by Django 5.0.1 on 2024-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('visitor', 'Visitor'), ('moderator', 'Moderator')], default='visitor', max_length=10),
        ),
    ]
