# Generated by Django 5.0.1 on 2024-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='comment_list',
            field=models.JSONField(default=list, null=True),
        ),
    ]
